import type { ConnectionsCategory } from '@/types/games';

export interface CategoryGroup {
  title: string;
  difficulty: 'yellow' | 'green' | 'blue' | 'purple';
  words: string[];
}

// 25+ groups per difficulty level
// Yellow = easiest, Purple = hardest/tricky
export const CATEGORY_POOL: CategoryGroup[] = [
  // ── YELLOW ──────────────────────────────────────────────────────────────
  { difficulty: 'yellow', title: 'Animals', words: ['BEAR', 'WOLF', 'LION', 'DEER', 'EAGLE', 'WHALE'] },
  { difficulty: 'yellow', title: 'Fruits', words: ['APPLE', 'MANGO', 'GRAPE', 'PEACH', 'PLUM', 'LIME'] },
  { difficulty: 'yellow', title: 'Colors', words: ['RED', 'BLUE', 'GREEN', 'GOLD', 'PINK', 'TEAL'] },
  { difficulty: 'yellow', title: 'Days of the Week', words: ['MONDAY', 'FRIDAY', 'SUNDAY', 'TUESDAY', 'THURSDAY', 'SATURDAY'] },
  { difficulty: 'yellow', title: 'Planets', words: ['MARS', 'VENUS', 'SATURN', 'NEPTUNE', 'URANUS', 'JUPITER'] },
  { difficulty: 'yellow', title: 'Vegetables', words: ['KALE', 'LEEK', 'BEET', 'YAMS', 'CORN', 'PEAS'] },
  { difficulty: 'yellow', title: 'Sports', words: ['GOLF', 'POLO', 'RUGBY', 'TENNIS', 'HOCKEY', 'BOXING'] },
  { difficulty: 'yellow', title: 'Musical Instruments', words: ['OBOE', 'LUTE', 'TUBA', 'DRUM', 'HARP', 'CELLO'] },
  { difficulty: 'yellow', title: 'Currencies', words: ['EURO', 'YEN', 'POUND', 'RUPEE', 'FRANC', 'DINAR'] },
  { difficulty: 'yellow', title: 'Gem Stones', words: ['RUBY', 'OPAL', 'JADE', 'TOPAZ', 'PEARL', 'AMBER'] },
  { difficulty: 'yellow', title: 'Trees', words: ['OAK', 'ELM', 'PINE', 'BIRCH', 'CEDAR', 'MAPLE'] },
  { difficulty: 'yellow', title: 'Weather', words: ['HAIL', 'SNOW', 'SLEET', 'FROST', 'STORM', 'DRIZZLE'] },
  { difficulty: 'yellow', title: 'Dances', words: ['TANGO', 'WALTZ', 'POLKA', 'RUMBA', 'SALSA', 'FOXTROT'] },
  { difficulty: 'yellow', title: 'Cheeses', words: ['BRIE', 'EDAM', 'FETA', 'GOUDA', 'COLBY', 'HAVARTI'] },
  { difficulty: 'yellow', title: 'Spices', words: ['CUMIN', 'MACE', 'SAGE', 'THYME', 'BASIL', 'CLOVE'] },
  { difficulty: 'yellow', title: 'Birds', words: ['WREN', 'ROBIN', 'FINCH', 'CRANE', 'RAVEN', 'SWIFT'] },
  { difficulty: 'yellow', title: 'Fish', words: ['CARP', 'BASS', 'TROUT', 'PERCH', 'TENCH', 'BREAM'] },
  { difficulty: 'yellow', title: 'Flowers', words: ['ROSE', 'IRIS', 'LILY', 'TULIP', 'ASTER', 'PANSY'] },
  { difficulty: 'yellow', title: 'Months', words: ['MARCH', 'APRIL', 'JUNE', 'JULY', 'AUGUST', 'OCTOBER'] },
  { difficulty: 'yellow', title: 'Clothing', words: ['VEST', 'CAPE', 'SKIRT', 'BLOUSE', 'SCARF', 'GLOVE'] },
  { difficulty: 'yellow', title: 'Drinks', words: ['COLA', 'MILK', 'CIDER', 'LAGER', 'MEAD', 'BRINE'] },
  { difficulty: 'yellow', title: 'Furniture', words: ['SOFA', 'DESK', 'SHELF', 'CHAIR', 'TABLE', 'BENCH'] },
  { difficulty: 'yellow', title: 'Dog Breeds', words: ['POODLE', 'BEAGLE', 'BOXER', 'HUSKY', 'COLLIE', 'SETTER'] },
  { difficulty: 'yellow', title: 'Professions', words: ['NURSE', 'CHEF', 'PILOT', 'JUDGE', 'MASON', 'CLERK'] },
  { difficulty: 'yellow', title: 'Shapes', words: ['OVAL', 'CUBE', 'CONE', 'PRISM', 'TORUS', 'HELIX'] },

  // ── GREEN ────────────────────────────────────────────────────────────────
  { difficulty: 'green', title: 'Types of Pasta', words: ['PENNE', 'RIGATONI', 'FUSILLI', 'FARFALLE', 'ORZO', 'ZITI'] },
  { difficulty: 'green', title: 'Famous Scientists', words: ['DARWIN', 'CURIE', 'NEWTON', 'TESLA', 'BOHR', 'HAWKING'] },
  { difficulty: 'green', title: 'Greek Gods', words: ['ZEUS', 'HERMES', 'APOLLO', 'ARES', 'HADES', 'POSEIDON'] },
  { difficulty: 'green', title: 'Norse Gods', words: ['ODIN', 'THOR', 'LOKI', 'FREYA', 'BALDUR', 'FRIGG'] },
  { difficulty: 'green', title: 'Card Games', words: ['POKER', 'BRIDGE', 'RUMMY', 'CANASTA', 'PIQUET', 'CRIBBAGE'] },
  { difficulty: 'green', title: 'Board Games', words: ['CHESS', 'DRAUGHTS', 'SCRABBLE', 'REVERSI', 'OTHELLO', 'CHECKERS'] },
  { difficulty: 'green', title: 'Constellations', words: ['ORION', 'LYRA', 'CYGNUS', 'PERSEUS', 'AQUILA', 'PISCES'] },
  { difficulty: 'green', title: 'World Capitals', words: ['ROME', 'LIMA', 'OSLO', 'BERN', 'SEOUL', 'CAIRO'] },
  { difficulty: 'green', title: 'Mountains', words: ['FUJI', 'DENALI', 'BLANC', 'WHITNEY', 'RAINIER', 'ELBRUS'] },
  { difficulty: 'green', title: 'Rivers', words: ['NILE', 'SEINE', 'RHINE', 'THAMES', 'GANGES', 'YANGTZE'] },
  { difficulty: 'green', title: 'Types of Bread', words: ['BRIOCHE', 'FOCACCIA', 'NAAN', 'PITA', 'CIABATTA', 'PRETZEL'] },
  { difficulty: 'green', title: 'Operas', words: ['TOSCA', 'AIDA', 'CARMEN', 'NORMA', 'OTELLO', 'NABUCCO'] },
  { difficulty: 'green', title: 'Languages', words: ['SWAHILI', 'URDU', 'GAELIC', 'LATIN', 'ARABIC', 'TAMIL'] },
  { difficulty: 'green', title: 'Cocktails', words: ['MOJITO', 'NEGRONI', 'GIMLET', 'SLING', 'BELLINI', 'COSMO'] },
  { difficulty: 'green', title: 'Olympic Sports', words: ['ARCHERY', 'FENCING', 'JUDO', 'LUGE', 'BIATHLON', 'EPEE'] },
  { difficulty: 'green', title: 'Shakespeare Plays', words: ['HAMLET', 'OTHELLO', 'MACBETH', 'TEMPEST', 'LEAR', 'PERICLES'] },
  { difficulty: 'green', title: 'Books of the Bible', words: ['GENESIS', 'EXODUS', 'RUTH', 'PSALMS', 'AMOS', 'HOSEA'] },
  { difficulty: 'green', title: 'Types of Hat', words: ['FEDORA', 'BERET', 'BOWLER', 'TRILBY', 'CLOCHE', 'BOATER'] },
  { difficulty: 'green', title: 'Martial Arts', words: ['JUDO', 'KARATE', 'AIKIDO', 'TAEKWONDO', 'KENDO', 'SUMO'] },
  { difficulty: 'green', title: 'Car Brands', words: ['HONDA', 'VOLVO', 'SKODA', 'LANCIA', 'SAAB', 'LOTUS'] },
  { difficulty: 'green', title: 'Cheeses (Advanced)', words: ['STILTON', 'GRUYERE', 'MANCHEGO', 'RICOTTA', 'PECORINO', 'TALEGGIO'] },
  { difficulty: 'green', title: 'Jazz Styles', words: ['BEBOP', 'FUSION', 'MODAL', 'SWING', 'RAGTIME', 'BOSSA'] },
  { difficulty: 'green', title: 'Dinosaurs', words: ['RAPTOR', 'STEGOSAUR', 'DIPLODOCUS', 'TRICERATOPS', 'BRONTOSAUR', 'ANKYLOSAUR'] },
  { difficulty: 'green', title: 'Poker Hands', words: ['FLUSH', 'STRAIGHT', 'TRIPS', 'BOAT', 'QUADS', 'PAIR'] },
  { difficulty: 'green', title: 'Phobias', words: ['ACROPHOBIA', 'ARACHNOPHOBIA', 'XENOPHOBIA', 'CYNOPHOBIA', 'ALGOPHOBIA', 'NYCTOPHOBIA'] },

  // ── BLUE ─────────────────────────────────────────────────────────────────
  { difficulty: 'blue', title: '___ Ball', words: ['BASKET', 'FOOT', 'BASE', 'VOLLEY'] },
  { difficulty: 'blue', title: '___ Smith', words: ['BLACK', 'GOLD', 'LOCK', 'WORD'] },
  { difficulty: 'blue', title: '___ Fish', words: ['SWORD', 'STAR', 'CAT', 'BLOW'] },
  { difficulty: 'blue', title: '___ Well', words: ['WISH', 'FARE', 'INK', 'STONE'] },
  { difficulty: 'blue', title: '___ Back', words: ['PAPER', 'SET', 'DRAW', 'PLAY'] },
  { difficulty: 'blue', title: '___ House', words: ['LIGHT', 'TREE', 'MANOR', 'FULL'] },
  { difficulty: 'blue', title: '___ Line', words: ['BASE', 'FINE', 'PUNCH', 'HAIR'] },
  { difficulty: 'blue', title: '___ Board', words: ['SKATE', 'SURF', 'CARD', 'SNOW'] },
  { difficulty: 'blue', title: '___ Work', words: ['FRAME', 'NET', 'FIELD', 'BENCH'] },
  { difficulty: 'blue', title: '___ Man', words: ['SUPER', 'SNOW', 'DOOR', 'IRON'] },
  { difficulty: 'blue', title: '___ Head', words: ['BALD', 'DEAD', 'BONE', 'HOT'] },
  { difficulty: 'blue', title: 'Double ___', words: ['CROSS', 'DUTCH', 'BASS', 'AGENT'] },
  { difficulty: 'blue', title: '___ Ring', words: ['BOX', 'EAR', 'KEY', 'SPRING'] },
  { difficulty: 'blue', title: '___ Bank', words: ['FOOD', 'RIVER', 'BLOOD', 'DATA'] },
  { difficulty: 'blue', title: '___ Light', words: ['SUN', 'MOON', 'SPOT', 'FLASH'] },
  { difficulty: 'blue', title: '___ Dog', words: ['HOT', 'SEA', 'CORN', 'BULL'] },
  { difficulty: 'blue', title: '___ Cat', words: ['TOM', 'WILD', 'FAT', 'COPY'] },
  { difficulty: 'blue', title: '___ Hand', words: ['BACK', 'SHORT', 'LONG', 'FREE'] },
  { difficulty: 'blue', title: 'Shades of Blue', words: ['AZURE', 'COBALT', 'NAVY', 'INDIGO'] },
  { difficulty: 'blue', title: 'Shades of Red', words: ['SCARLET', 'CRIMSON', 'MAROON', 'CHERRY'] },
  { difficulty: 'blue', title: '___ Fire', words: ['CAMP', 'CROSS', 'BACK', 'OPEN'] },
  { difficulty: 'blue', title: '___ Egg', words: ['HARD', 'NEST', 'ROTTEN', 'OVER'] },
  { difficulty: 'blue', title: '___ Stone', words: ['LIME', 'SAND', 'BROWN', 'KEY'] },
  { difficulty: 'blue', title: '___ Watch', words: ['STOP', 'NIGHT', 'DEATH', 'DOG'] },
  { difficulty: 'blue', title: '___ Key', words: ['DON', 'MON', 'TURN', 'OFF'] },

  // ── PURPLE ────────────────────────────────────────────────────────────────
  { difficulty: 'purple', title: 'Things that can be "broken"', words: ['RECORD', 'PROMISE', 'SILENCE', 'GROUND'] },
  { difficulty: 'purple', title: 'Things that "run"', words: ['NOSE', 'CLOCK', 'STOCKING', 'MASCARA'] },
  { difficulty: 'purple', title: 'Things that can be "cracked"', words: ['CODE', 'JOKE', 'SAFE', 'EGG'] },
  { difficulty: 'purple', title: '___ POT', words: ['HOT', 'JACK', 'FLOWER', 'CRACKER'] },
  { difficulty: 'purple', title: 'Follow "OVER"', words: ['BOARD', 'HAUL', 'RULE', 'COAT'] },
  { difficulty: 'purple', title: 'Follow "UNDER"', words: ['COVER', 'MINE', 'TONE', 'TAKE'] },
  { difficulty: 'purple', title: 'Precede "YARD"', words: ['BACK', 'JUNK', 'COURT', 'CHURCH'] },
  { difficulty: 'purple', title: 'Precede "SIDE"', words: ['BLIND', 'WRONG', 'OUT', 'RING'] },
  { difficulty: 'purple', title: 'Can follow "THUNDER"', words: ['BOLT', 'STORM', 'CLAP', 'BIRD'] },
  { difficulty: 'purple', title: 'Words that sound like letters', words: ['ARE', 'BEE', 'SEA', 'WHY'] },
  { difficulty: 'purple', title: '"BREAK" + ___', words: ['DOWN', 'FAST', 'OUT', 'THROUGH'] },
  { difficulty: 'purple', title: 'Words containing "OWL"', words: ['FOWL', 'GROWL', 'PROWL', 'SCOWL'] },
  { difficulty: 'purple', title: 'One letter from "GAME"', words: ['NAME', 'FAME', 'CAME', 'SAME'] },
  { difficulty: 'purple', title: 'Can precede "WORK"', words: ['FRAME', 'GROUND', 'NET', 'PAPER'] },
  { difficulty: 'purple', title: 'Palindromes', words: ['LEVEL', 'CIVIC', 'MADAM', 'RADAR'] },
  { difficulty: 'purple', title: 'Words that are also verbs meaning "to hit"', words: ['BELT', 'CLOCK', 'SWAT', 'BASH'] },
  { difficulty: 'purple', title: 'Follow "BLACK"', words: ['BIRD', 'BOARD', 'OUT', 'MAIL'] },
  { difficulty: 'purple', title: 'Follow "FIRE"', words: ['WORKS', 'SIDE', 'PLACE', 'LIGHT'] },
  { difficulty: 'purple', title: 'Hidden body parts', words: ['SHIRT', 'HELLO', 'BRACE', 'SNAIL'] },
  { difficulty: 'purple', title: 'Hidden planets', words: ['WARMER', 'URANIUM', 'SATURN', 'MARVEL'] },
  { difficulty: 'purple', title: 'Things that can be "flat"', words: ['TYRE', 'RATE', 'CAP', 'IRON'] },
  { difficulty: 'purple', title: 'Words ending in silent letters', words: ['LAMB', 'WRAP', 'DEBT', 'ISLE'] },
  { difficulty: 'purple', title: 'Can precede "BERRY"', words: ['BLUE', 'STRAW', 'GOOSE', 'RASP'] },
  { difficulty: 'purple', title: 'Can follow "SUN"', words: ['BURN', 'FLOWER', 'RISE', 'LIGHT'] },
  { difficulty: 'purple', title: 'Things that "float"', words: ['BOAT', 'IDEA', 'STOCK', 'BALLOT'] },
];

// Re-export ConnectionsCategory so callers can import from here if needed
export type { ConnectionsCategory };
