import type { SpellingBeePuzzle } from '@/types/games';

export const SPELLING_BEE_PUZZLES: SpellingBeePuzzle[] = [
  {
    centerLetter: 'T',
    outerLetters: ['A', 'R', 'E', 'S', 'I', 'N'],
    validWords: ['TRAIN', 'STRAIN', 'RETAIN', 'STAIN', 'SAINT', 'SATIN', 'ANTI', 'RANT', 'RAIN', 'REIN', 'RENT', 'TENT', 'TEST', 'NEST', 'REST', 'SENT', 'INSET', 'INTER', 'ENTER', 'STARE', 'STIR', 'TIRE', 'TIER', 'TIES', 'SITE', 'STEIN', 'TRANSIT', 'ENTRAIN', 'STRAINER', 'NITRATE', 'ATTIRE', 'NASTIER', 'INTEREST', 'NATTER', 'TAINT', 'TRITE', 'ENTIRE', 'INERT', 'NITRITE'],
    pangrams: ['STRAINER', 'NASTIER'],
  },
  {
    centerLetter: 'L',
    outerLetters: ['A', 'P', 'E', 'C', 'O', 'U'],
    validWords: ['PLACE', 'PALACE', 'EQUAL', 'VOCAL', 'LOCAL', 'OCTAL', 'COAL', 'CLAP', 'CLUE', 'CALL', 'TALL', 'TALE', 'PALE', 'POLE', 'ROLE', 'LACE', 'LOPE', 'CAPE', 'COPE', 'COLA', 'COUPLE', 'LOCALE', 'CAPSULE', 'ALLOCATE', 'COPULA'],
    pangrams: ['CAPSULE', 'COPULA'],
  },
  {
    centerLetter: 'R',
    outerLetters: ['G', 'A', 'E', 'N', 'D', 'I'],
    validWords: ['RANGE', 'GRAND', 'GRADE', 'GRAIN', 'GRIND', 'DRAIN', 'RAINED', 'RANGED', 'RAISED', 'DARING', 'READING', 'RIDGE', 'REIGN', 'RIND', 'RING', 'REIN', 'RAID', 'RAIN', 'RIDER', 'RENDER', 'REGARD', 'GANDER', 'DANGER', 'GARDEN', 'GARNER', 'DINER', 'GENDER', 'GIRDER', 'GRADER', 'GRANDER', 'DERANGE', 'RANCHING'],
    pangrams: ['DERANGE', 'GRANDER'],
  },
  {
    centerLetter: 'S',
    outerLetters: ['T', 'A', 'R', 'E', 'N', 'O'],
    validWords: ['STONE', 'STORE', 'STARE', 'SNARE', 'SNORE', 'NOTES', 'TONES', 'ONES', 'EONS', 'NOSE', 'ROSE', 'TORE', 'SORE', 'SCORE', 'STONER', 'SENATE', 'SENSOR', 'SENTRY', 'SONNET', 'REASON', 'SEASON', 'ARENAS', 'SERENE', 'EASTERN', 'NEAREST', 'SENATOR'],
    pangrams: ['SENATOR', 'EASTERN'],
  },
  {
    centerLetter: 'N',
    outerLetters: ['O', 'I', 'T', 'A', 'C', 'E'],
    validWords: ['OCEAN', 'ACTION', 'NOTION', 'NATION', 'COIN', 'CONE', 'NONE', 'TONE', 'TENT', 'NICE', 'NINE', 'NEON', 'NOTE', 'ANTE', 'INTO', 'NIECE', 'TONIC', 'ATONE', 'CANOE', 'NOTICE', 'ANOINT', 'INNOCENT', 'CONTAIN', 'ANOINTED', 'ANNOTATE', 'ANTENNA', 'CREATION', 'CAUTION'],
    pangrams: ['CREATION', 'CAUTION'],
  },
  {
    centerLetter: 'M',
    outerLetters: ['A', 'P', 'L', 'E', 'S', 'C'],
    validWords: ['MAPLE', 'PLACE', 'CLAIM', 'CLAMP', 'AMPLE', 'CAMP', 'CAME', 'LAME', 'MALE', 'SAME', 'SCALE', 'SCAM', 'SLAM', 'CLAM', 'PALM', 'CALM', 'MEAL', 'MAPLES', 'SAMPLE', 'ACCLAIM', 'MECHANISM'],
    pangrams: ['EXAMPLE', 'SAMPLE'],
  },
  {
    centerLetter: 'B',
    outerLetters: ['R', 'A', 'I', 'D', 'E', 'L'],
    validWords: ['BRIDE', 'BLADE', 'BRAID', 'BREAD', 'BIRDIE', 'BRIDLE', 'BRIDAL', 'BARREL', 'BARE', 'DARE', 'DRAB', 'BALE', 'BEAD', 'BIRD', 'BILE', 'ROBE', 'BRED', 'BIER', 'IDEA', 'IDLE', 'ARID', 'BRAD', 'LIBERATED', 'CALIBER', 'RELIABLE'],
    pangrams: ['BRIDLE', 'LIBERATED'],
  },
  {
    centerLetter: 'G',
    outerLetters: ['R', 'O', 'W', 'I', 'N', 'E'],
    validWords: ['GROWN', 'GROIN', 'GOWN', 'GORE', 'WORE', 'WIRE', 'WINE', 'GROW', 'GENE', 'GRIN', 'REIGN', 'IRONING', 'GROWING', 'NITROGEN', 'GROANING'],
    pangrams: ['GROWING', 'NITROGEN'],
  },
  {
    centerLetter: 'F',
    outerLetters: ['L', 'U', 'T', 'E', 'R', 'A'],
    validWords: ['FLUTE', 'FAULT', 'FLARE', 'AFTER', 'FLAIR', 'FARE', 'FATE', 'FLAT', 'FEAT', 'FELT', 'FUEL', 'FRAT', 'EARL', 'LURE', 'LUTE', 'LATE', 'RATE', 'RULE', 'TALE', 'TRAIL', 'FLUTTER', 'FAILURE', 'FATEFUL', 'GRATEFUL', 'ARTFUL', 'TEARFUL'],
    pangrams: ['FLUTTER', 'GRATEFUL'],
  },
  {
    centerLetter: 'C',
    outerLetters: ['H', 'A', 'R', 'M', 'O', 'N'],
    validWords: ['CHARM', 'RANCH', 'MARCH', 'ARCH', 'CORN', 'HORN', 'NORM', 'NARC', 'COMA', 'ROAM', 'MOCHA', 'CONCH', 'CROON', 'MANOR', 'HONOR', 'ANCHOR', 'MONARCH', 'MAROON', 'MACRON', 'CHRONIC', 'CANNON', 'HARMONY', 'HONORARY'],
    pangrams: ['MONARCH', 'HARMONY'],
  },
  {
    centerLetter: 'P',
    outerLetters: ['A', 'I', 'N', 'T', 'E', 'R'],
    validWords: ['PAINT', 'PRINT', 'PINT', 'PINE', 'PANE', 'PEAR', 'PIER', 'PAIR', 'REIN', 'RAIN', 'TRIP', 'TRAP', 'TAPE', 'TARP', 'PLANE', 'PLANER', 'PLIANT', 'PAINTER', 'PINTAIL', 'CAPTAIN', 'CURTAIN', 'PARTISAN', 'PIRATING'],
    pangrams: ['PAINTER', 'PIRATING'],
  },
  {
    centerLetter: 'W',
    outerLetters: ['I', 'L', 'D', 'E', 'R', 'N'],
    validWords: ['WIELD', 'WILDER', 'ROWED', 'WIDER', 'LINED', 'RILED', 'DINER', 'RIDER', 'DRIED', 'MILD', 'WILD', 'WILE', 'WINE', 'WIRE', 'WREN', 'LIEN', 'LEND', 'WIND', 'DWINDLE', 'WINDING', 'REWINDING'],
    pangrams: ['DWINDLE', 'WILDER'],
  },
  {
    centerLetter: 'V',
    outerLetters: ['I', 'O', 'L', 'E', 'T', 'N'],
    validWords: ['VIOLET', 'NOVEL', 'VOTED', 'VOTE', 'VOLE', 'VINE', 'VEIL', 'VENT', 'VEIN', 'VOLT', 'TONE', 'TOIL', 'TILE', 'INLET', 'ELITE', 'LIVEN', 'OLIVES', 'VIOLIN', 'VIOLENT', 'INVOLVE', 'NOVELIST', 'EVOLUTION', 'INVENTION'],
    pangrams: ['VIOLENT', 'EVOLUTION'],
  },
  {
    centerLetter: 'D',
    outerLetters: ['R', 'A', 'G', 'O', 'N', 'E'],
    validWords: ['DRAGON', 'GROAN', 'DRONE', 'DOER', 'DARE', 'DEAR', 'DEER', 'DONE', 'DOTE', 'EARN', 'GORE', 'GONE', 'NERD', 'NODE', 'ROAD', 'RODE', 'DRONED', 'GARDEN', 'ORANGE', 'GROANED', 'RANGED', 'DONGER', 'DRAGONET', 'GRANDEUR'],
    pangrams: ['DRAGON', 'GRANDEUR'],
  },
  {
    centerLetter: 'K',
    outerLetters: ['I', 'T', 'C', 'H', 'E', 'N'],
    validWords: ['KITCHEN', 'THICKEN', 'CHIT', 'INCH', 'ITCH', 'NICK', 'KICK', 'NECK', 'KENT', 'TECH', 'NICHE', 'THICK', 'THINK', 'KNIT', 'KITE', 'CITE', 'TICK', 'HINT', 'HIKE', 'CHICKEN', 'THICKET', 'CHECKING', 'THINNING'],
    pangrams: ['KITCHEN', 'THICKEN'],
  },
  {
    centerLetter: 'H',
    outerLetters: ['E', 'A', 'R', 'T', 'S', 'B'],
    validWords: ['HEART', 'HEARTH', 'EARTH', 'BASTE', 'BEAST', 'BEARS', 'HEARD', 'HEARS', 'HASTE', 'HATER', 'SHARE', 'SHEAR', 'STARE', 'BREAD', 'BREATHE', 'BREATH', 'HERBS', 'HARES', 'HERD', 'HERE', 'HATE', 'HARE', 'THEATRE', 'BREATHES', 'HEARTBEAT'],
    pangrams: ['BREATHE', 'THEATRE'],
  },
  {
    centerLetter: 'O',
    outerLetters: ['C', 'E', 'A', 'N', 'I', 'S'],
    validWords: ['OCEAN', 'IONIC', 'ICON', 'COIN', 'CONE', 'ONCE', 'INCA', 'ANION', 'CANOE', 'ACNE', 'NICE', 'NINE', 'NOON', 'NONE', 'NOTE', 'NEON', 'INCOME', 'COCAINE', 'CONTAIN', 'CONNOTE', 'ANOINTED', 'CANONIZE'],
    pangrams: ['COCAINE', 'CANONIZE'],
  },
  {
    centerLetter: 'E',
    outerLetters: ['M', 'B', 'R', 'A', 'C', 'I'],
    validWords: ['EMBRACE', 'CAMERA', 'BRACE', 'CREAM', 'CRIME', 'MICE', 'RICE', 'RACE', 'CRAM', 'CAME', 'REAM', 'CARE', 'BARE', 'MACABRE', 'BARRIER', 'CERAMIC', 'EMBRACED'],
    pangrams: ['EMBRACE', 'CERAMIC'],
  },
  {
    centerLetter: 'I',
    outerLetters: ['N', 'D', 'U', 'S', 'T', 'R'],
    validWords: ['INDUCT', 'STIR', 'DUSTY', 'DIRTY', 'TRUST', 'TURNS', 'RUINS', 'RUIN', 'STUD', 'UNIT', 'UNTIL', 'TURDS', 'INDUSTRY', 'DISTINCT', 'INSTRUCT'],
    pangrams: ['INDUSTRY', 'DISTINCT'],
  },
  {
    centerLetter: 'A',
    outerLetters: ['B', 'S', 'T', 'R', 'C', 'E'],
    validWords: ['ABSTRACT', 'BASTE', 'CASTE', 'TRACE', 'STARE', 'CRATE', 'TEARS', 'BEARS', 'ACRES', 'CARES', 'BRACE', 'RECAST', 'CREASE', 'TEASER', 'BEATER', 'REBATE', 'BREAST', 'CABARET', 'ARCADES'],
    pangrams: ['ABSTRACT', 'CABARET'],
  },
  {
    centerLetter: 'U',
    outerLetters: ['N', 'D', 'E', 'R', 'W', 'O'],
    validWords: ['UNDER', 'WONDER', 'DONOR', 'DRONE', 'OWNED', 'DOWER', 'ORDER', 'ROWED', 'DONNER', 'UNDONE', 'RENOWN', 'ENDOW', 'ROUND', 'WOUND', 'RENOWNED', 'DUNGEON', 'WONDER', 'UNWOUND', 'REBOUND'],
    pangrams: ['RENOWNED', 'UNWOUND'],
  },
  {
    centerLetter: 'W',
    outerLetters: ['A', 'T', 'E', 'R', 'F', 'L'],
    validWords: ['WATER', 'LATER', 'FLARE', 'FLOAT', 'FLUTE', 'AFTER', 'AWFUL', 'TALE', 'FLAT', 'FLAW', 'LURE', 'WORE', 'WELT', 'WARE', 'WART', 'WALE', 'TRAWL', 'FLATTER', 'FLUTTER', 'WATERFALL', 'FLATWARE'],
    pangrams: ['WATERFALL', 'FLATWARE'],
  },
  {
    centerLetter: 'S',
    outerLetters: ['P', 'A', 'R', 'K', 'L', 'E'],
    validWords: ['SPARK', 'SPARE', 'SPEAR', 'SPEAK', 'PEARL', 'ARLES', 'LASER', 'PARKA', 'KALE', 'PALE', 'PALER', 'LACE', 'LAKE', 'RAKE', 'LARK', 'SPARKLE', 'RELAPSE', 'EXAMPLES'],
    pangrams: ['SPARKLE', 'RELAPSE'],
  },
  {
    centerLetter: 'H',
    outerLetters: ['U', 'M', 'B', 'L', 'E', 'D'],
    validWords: ['HUMBLE', 'BUMBLE', 'RUMBLE', 'TUMBLE', 'MUMBLE', 'DUMB', 'HELD', 'HELM', 'HELP', 'MELD', 'MULE', 'BLUE', 'LUBE', 'LUMP', 'PLUM', 'SLUM', 'HURL', 'HUMBLED', 'MUMBLED', 'CRUMBLED'],
    pangrams: ['HUMBLED', 'STUMBLE'],
  },
  {
    centerLetter: 'T',
    outerLetters: ['H', 'U', 'N', 'D', 'E', 'R'],
    validWords: ['THUNDER', 'HUNTER', 'UNDER', 'RENTED', 'TENDER', 'TURNED', 'TUNED', 'TREND', 'DETER', 'ENTER', 'HERD', 'HUNT', 'HURT', 'REND', 'RENT', 'TUNE', 'HUNTED', 'UNTIED', 'THUNDERED'],
    pangrams: ['THUNDER', 'THUNDERED'],
  },
  {
    centerLetter: 'P',
    outerLetters: ['L', 'U', 'M', 'B', 'E', 'R'],
    validWords: ['PLUMBER', 'LUMBER', 'RUMBLE', 'BUMPER', 'SLUMBER', 'PLUMB', 'PUMP', 'PULP', 'PURE', 'BLUR', 'BLUE', 'LURE', 'RULE', 'RUBLE', 'TUMBLE', 'PURPLE', 'BURBLE', 'CRUMPLE', 'TREMBLE'],
    pangrams: ['PLUMBER', 'SLUMBER'],
  },
  {
    centerLetter: 'G',
    outerLetters: ['A', 'R', 'D', 'E', 'N', 'I'],
    validWords: ['GARDEN', 'DANGER', 'GAINED', 'RAINED', 'RANGED', 'RIDGE', 'GRIND', 'GRADE', 'GRAIN', 'REIGN', 'DARING', 'READING', 'GANDER', 'GARNER', 'GENDER', 'GIRDER', 'GRADER', 'DERANGE', 'GARDENIA'],
    pangrams: ['GARDENIA', 'DERANGE'],
  },
  {
    centerLetter: 'C',
    outerLetters: ['O', 'M', 'P', 'L', 'E', 'X'],
    validWords: ['COMPLEX', 'COMPEL', 'COMPLY', 'EXCEL', 'EMPEL', 'COME', 'COPE', 'COLE', 'POLE', 'MOLE', 'POEM', 'CLOP', 'PLOP', 'PLEX', 'COMPLEX', 'EXPLORE', 'COMPLEXION'],
    pangrams: ['COMPLEX', 'COMPLEXION'],
  },
  {
    centerLetter: 'B',
    outerLetters: ['U', 'T', 'T', 'E', 'R', 'F'],
    validWords: ['BUTTER', 'BETTER', 'BUFFER', 'BUFFET', 'REBUFF', 'BUTTE', 'BRUTE', 'TRUER', 'TUBER', 'DEBUT', 'REBUT', 'BLUFF', 'GRUFF', 'STUFF', 'BUTTERFLY', 'BUTTERNUT'],
    pangrams: ['BUTTERFLY', 'BUTTERNUT'],
  },
  {
    centerLetter: 'M',
    outerLetters: ['O', 'U', 'N', 'T', 'A', 'I'],
    validWords: ['MOUNTAIN', 'MAINTAIN', 'MUTTON', 'MOTION', 'NATION', 'RATION', 'UNION', 'ONION', 'AMINO', 'TONIC', 'MAIM', 'MAIN', 'MINT', 'MOAN', 'MOAT', 'MOON', 'MOUNT', 'OUNCE', 'AMOUNT', 'AUTOMATION', 'ANIMATION', 'MOUNTAIN'],
    pangrams: ['MOUNTAIN', 'ANIMATION'],
  },
];
